; COPY THE STRING FORM ONE LOCATION TO ANOTHER

DATA SEGMENT
STR_SOURCE DB 'COPY THIS STRING'
COUNT DB 10H
DATA ENDS

EXTRA SEGMENT
DEST_STR DB '                '
EXTRA ENDS

CODE SEGMENT
	ASSUME CS:CODE, DS:DATA, ES:EXTRA
START:
	MOV AX,DATA
	MOV DS,AX
	MOV AX,EXTRA
	MOV ES,AX
	LEA SI,STR_SOURCE
	LEA DI,DEST_STR
	MOV CL,COUNT
	MOV CH,00H
	REP MOVSB	; REP -> DEC CX AND REPEAT TILL CX=0 // MOVSB DS:[SI] -> ES:[DI]
	HLT
CODE ENDS
	END